[package]
name = "genuine-chip8-emulator-rust"
version = "0.1.0"
authors = ["Kumar Ravi <rdahiya0213@gmail.com>", "Abhinav Tripathi <genuineabhinav@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
time = "0.1.42"
chrono = "0.4"
